---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Initialize role
      ansible.builtin.include_role:
        name: lstig.gpg
        tasks_from: init
        public: true

    - name: Check gpg command
      ansible.builtin.command:
        cmd: gpg --version
